version: '3'

tasks:
  rebuild:
    desc: Rebuild the dev container with the Dev Containers CLI
    preconditions:
      - sh: command -v devcontainer >/dev/null 2>&1
        msg: "Dev Containers CLI is not installed. Install with: npm i -g @devcontainers/cli"
    cmds:
      - devcontainer up --workspace-folder . --remove-existing-container --log-level trace
    silent: false
  upgrade:self:
    desc: Refresh the .devcontainer directory from the canonical repository
    dir: ..
    cmds:
      - curl -fsSL https://raw.githubusercontent.com/emsilva/devcontainer/main/install.sh | sh
    silent: false

  upgrade:codex:
    desc: Download and install the latest Codex CLI without rebuilding the container
    dir: .devcontainer
    cmds:
      - ./scripts/upgrade-codex.sh
    silent: false
